server:
  port: 8120

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/practiceproject?createDatabaseIfNotExist=true
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql:true:
    generate-ddl: true
    open-in-view: true
    show-sql: false

  sleuth:
    enabled: true

  sql:
    init:
      mode: always

  # Redis Config
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

  thymeleaf:
    mode: HTML